name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  CI:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        project: [ "Mavanmanen.Core/Mavanmanen.Core.csproj", "Mavanmanen.Core.Wpf/Mavanmanen.Core.Wpf.csproj" ]
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
        include-prerelease: true
    - name: Install dependencies
      run: dotnet restore ${{ matrix.project }}
    - name: Build
      run: dotnet build --configuration Release --no-restore ${{ matrix.project }}
    - name: Test
      run: dotnet test --filter ${{ matrix.project }}
    - name: Publish to NuGet
      uses: brandedoutcast/publish-nuget@v2
      with:
        PROJECT_FILE_PATH: ${{ matrix.project }}
        VERSION_REGEX: '^\s*<PackageVersion>(.*)<\/PackageVersion>\s*$'
        NUGET_KEY: ${{secrets.NUGET_API_KEY}}
        TAG_COMMIT: false
